### ISSUE TITLE
This is a license violation. Remove it now.

### ISSUE THREAD

**Issue by robinwatts** [geek5nan/AndroidMuPDFDemo#2]
MuPDF is released as open source under the GNU AGPL license. You are breaking this license by not including the license, or the source, or a pointer to where you can get the source.

Either comply with the license, or take this down, now.

**Comment by geek5nan** [comment]
Thank you for reminding,I have add the license in this repo.

**Comment by robinwatts** [comment]
Thanks. You should also include either:

1) A copy of the source you used
or 2) A pointer to the copy of the source you used, plus any changes.

People need to be able to recreate the binary libraries that you ship.

Thanks!
